### ISSUE TITLE
Windows installer: make service startup optional

### ISSUE THREAD

**Issue by inikulshin** [rabbitmq/rabbitmq-packaging#12]
It's a very common practice - to ask user whether to run/launch installed software or not.

Sometimes, after upgrade, service start don't have a chance to succeed immediately after installing - for example, if some enabled plugins are custom and must be copied to RABBITMQ_HOME before starting.

We (Varonis) are also interested in disabling `packaging/windows-exe/rabbitmq_nsi.in`'s `rabbitmq-service.bat start` it in **silent mode** - either conditionally, with command line flag, or unconditionally (`IfSilent`).

**Comment by michaelklishin** [comment]
@inikulshin what version of Windows are you running? It's likely that we indeed run an outdated versio of `makensis`.

**Comment by inikulshin** [comment]
@michaelklishin 

I found the breaking change (in `makensis` version [3.07](https://nsis.sourceforge.io/Docs/AppendixF.html#v3.07-cl))

> F.3.2.1 Major Changes
> [Unicode](https://nsis.sourceforge.io/Docs/Chapter4.html#aunicodetarget) now defaults to true

And `ExecDos` doesn't support Unicode.

Adding `Unicode false` as a first line resolves.

**Comment by michaelklishin** [comment]
@inikulshin good find. What do you think about submitting a PR?

**Comment by inikulshin** [comment]
@michaelklishin it is almost ready.

Do you want to preserve `rabbitmqctl start` in **silent** mode? Will it be it too breaking to remove it?

I moved `rabbitmqctl start` from section to the final window (separated `install` and `start`), but  final window's command is skipped in silent mode by design. I can workaround, but is it really necessary (for silent mode)?

From our experience it is better to run `rabbitmqctl start` from script separately: to complete installation actions (config, plugins), to get the logs. Actually, for us RabbitMQ service in running state after installation is only a pain: we should stop it immediately before I found a "hack": to rename `erlsrv.exe` before running RabbitMQ installer and to cause `rabbitmqctl start` to fail.
