### ISSUE TITLE
Windows installer: plug-in installation directory ends up on drive C when installation directory is overridden to use another drive 

### ISSUE THREAD

**Issue by pechn** [rabbitmq/rabbitmq-packaging#28]
When installing RabbitMQ server using the exe installer "rabbitmq-server-3.11.2.exe", if I change the install directory to the path in another disk such as "**D**:\Program Files\RabbitMQ Server", the RabbitMQ service will not be started normally but with error "system error 1067". After looking for the cause many hours, I found the cause was that the RabbitMQ plugins directory was not set correctly. The plugins directory was STILL placed to "**C**:\Program Files\RabbitMQ Server" after the installation although I had changed the install directory.
The recent windows exe installer may have the same problem, not just the one "rabbitmq-server-3.11.2.exe".
Please have a check.

Platform env.: Windows 10 or Windows 11

**Comment by michaelklishin** [comment]
The insoles is open source software. You can have a look yourself since you understand the problem to some extent already. The source can be found in this repo.

**Comment by lukebakken** [comment]
Yep, I can reproduce it. Investigating a fix now.

**Comment by lukebakken** [comment]
@pechn as a workaround, specify the installation directory on the command line:

```
.\rabbitmq-server-3.11.2.exe /D=C:\ProgramData\RabbitMQ-Server
```

That works as expected. It seems that internal vars aren't updated when you use the dialog to specify an installation directory.

**Comment by lukebakken** [comment]
Please see #29. I'm pretty sure that's the correct fix but I'd like @inikulshin or @dumbbell to double-check.

**Comment by inikulshin** [comment]
@lukebakken look's good.

Maybe the code block you **copied** should be **moved**? The first place is overridden anyway.

**Comment by pechn** [comment]
> @pechn as a workaround, specify the installation directory on the command line:
> 
> ```
> .\rabbitmq-server-3.11.2.exe /D=D:\Program Files\RabbitMQ Server
> ```
> 
> Note that `/D` _must_ be the last argument and that you should **not** double-quote the argument, even if it has spaces.
> 
> That works as expected. It seems that internal vars aren't updated when you use the dialog to specify an installation directory.

@lukebakken Thanks for the solution. Actually I had managed to install it with the zip packaged file [rabbitmq-server-windows-3.11.2.zip](https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.11.2/rabbitmq-server-windows-3.11.2.zip) . Good to hear that the next release of the windows exe installer will be fixed.:)
