### ISSUE TITLE
RabbitMQ uninstall.exe is not digitally signed

### ISSUE THREAD

**Issue by ophirzk** [rabbitmq/rabbitmq-packaging#40]
Hi,

The RabbitMQ installer, rabbitmq-server.exe, is signed by VMWare but uninstall.exe is not signed.

That can cause the uninstall.exe to be blocked from executing and might expose RabbitMQ users in Windows to attacks that pretend they are RabbitMQ's uninstall.exe.

Can the uninstall.exe be signed the same way as the installation exe is signed?

Version checked: 3.10.8.

**Comment by michaelklishin** [comment]
You are welcome to contribute any [relevant changes to the installer](https://github.com/rabbitmq/rabbitmq-packaging/tree/main/windows-exe). I do realize there may be changes necessary in the release pipeline but everything else is open source.

**Comment by ophirzk** [comment]
I assumed that there should be changes only in the release pipeline and not in the code.

There should be changes in the installer as well?

**Comment by michaelklishin** [comment]
@ophirzk I don't know, you are welcome to investigate this

**Comment by lukebakken** [comment]
Unfortunately this is not easily solved. We sign the `.exe` installer using [`osslsigncode`]
(https://github.com/rabbitmq/rabbitmq-ci/blob/89a4488cdc4421eaa6cbf2f4bc55e1a930b367a8/server-release/scripts/build-package.sh#L242-L271) as part of our Linux-based packaging process.

The NSIS installer file specifies that `uninstall.exe` is written _at install time_ here: [link](https://github.com/rabbitmq/rabbitmq-packaging/blob/main/windows-exe/rabbitmq_nsi.in#L148)

Here are the relevant docs for signing an un-installer:
* https://nsis.sourceforge.io/Signing_an_Uninstaller
* https://nsis.sourceforge.io/Docs/Chapter5.html#uninstfinalize

Neither of those processes will work given our current pipeline. I honestly don't think it's worth the effort. I'll leave this issue open for a few days in case anyone else wants to chime in.

**Comment by ophirzk** [comment]
@lukebakken 
Can you please elaborate more on why it won't work with the current pipeline?

I think it is worth solving, there is no reason to have the uninstall.exe unsigned especially when the installer is signed, and in Linux, everything is signed. Windows should not be different.

**Comment by lukebakken** [comment]
> Can you please elaborate more on why it won't work with the current pipeline?

The code is private, so I can't share it. But the installer is built on Linux. To "pre-create" the "uninstall.exe" file (https://nsis.sourceforge.io/Signing_an_Uninstaller), we would have to figure out how to run the installer on Windows, and then package up the signed uninstall file.

The second option, using `!uninstfinalize` won't work because we'd have to ship our signing cert and key with the installer.

If we had even one RabbitMQ customer who paid for a license we'd consider this, but as of now no paying customers have even noticed that `uninstall.exe` is not signed. This is probably due to the fact that the general practice of NSIS installers is to write the `uninstall.exe` file at install-time. Since you trust the installer you should then trust the generated `uninstall.exe` file.

**Comment by lukebakken** [comment]
> I'm 100% sure that !uninstfinalize and !finalize commands do not require to ship any cert or key with the installer.

Well, that's incorrect.

Here is the command that signs the installer. Note that it requires certificates, which we can't ship:

```
    osslsigncode sign \
      -certs "code-signing-cert/code-signing-cert/vmware-inc.crt" \
      -key "code-signing-cert/code-signing-cert/vmware-inc.key" \
      -n "RabbitMQ Server $VERSION Setup" \
      -i http://www.rabbitmq.com/ \
      -t http://timestamp.digicert.com \
      -in "PACKAGES/rabbitmq-server-$VERSION.exe.unsigned" \
      -out "PACKAGES/rabbitmq-server-$VERSION.exe"
```

**Comment by inikulshin** [comment]
@lukebakken what do you mean by "ship"?

If you run this command in `!uninstfinalize`/`!finalize` (with different `-in` and `-out`), it **will not** cause `crt`/`key` to be in the `rabbitmq-server-$VERSION.exe`. Its content is configured by `nsi` file...

Maybe you mean that `crt`/`key` files are not available during `makensis` run?

**Comment by lukebakken** [comment]
I misunderstood the documentation. I thought that `!uninstfinalize` was run during the installation of the `.exe` file, instead of when it's being built.

We'll take a look at changing the CI pipeline to accommodate this, but it's not high priority.

**Comment by inikulshin** [comment]
Meanwhile I can create a PR with a necessary changes.

I think, the best is `!uninstfinalize 'if exist sign.bat sign.bat "%1"'` or similar. This way you shouldn't expose anything related to signing. Just implement `sign.bat` and copy it before making the installer.

However, `!uninstfinalize` is added to `makensis` since [3.08](https://nsis.sourceforge.io/Docs/AppendixF.html#v3.08-cl) only. Do you already have it? [Last time](https://github.com/rabbitmq/rabbitmq-packaging/pull/15#issuecomment-1208388231) is was **v3.06.1-1**.

**Comment by lukebakken** [comment]
The `.exe` installer is built on Linux, not Windows, and the code is private. You won't be able to create a PR for that. Creating a PR for the NSIS input file is the least of our worries 😉 

We'll get to this issue when we have time.

**Comment by inikulshin** [comment]
I'm not familiar with Debian, but it looks like `nsis` **3.08** is available as `testing`/`unstable`: https://tracker.debian.org/pkg/nsis
I don't know if it's relevant...

**Comment by ophirzk** [comment]
@lukebakken in what version is it planned to be addressed?

**Comment by michaelklishin** [comment]
@ophirzk Luke's comment from May 30 still stands

**Comment by lhoguin** [comment]
For what it's worth, OTP team were not convinced and closed the companion to this ticket: https://github.com/erlang/otp/issues/7002

To move this forward I would recommend convincing the Erlang/OTP team to sign their uninstall.exe, since RabbitMQ depends on Erlang/OTP. This issue can only be fully resolved when both Erlang/OTP and RabbitMQ have their uninstall.exe signed.

**Comment by IngelaAndin** [comment]
You would have to explain the perceived problem in much more detail. What tool  is it that cause the uninstaller to be blocked, and why is this our problem?

**Comment by lukebakken** [comment]
@inikulshin @ophirzk -
* https://github.com/rabbitmq/rabbitmq-server-binaries-dev/releases/tag/v4.0.0-alpha.181
* https://github.com/rabbitmq/rabbitmq-server-binaries-dev/releases/download/v4.0.0-alpha.181/rabbitmq-server-4.0.0-alpha.181.exe

**Comment by michaelklishin** [comment]
@IngelaAndin it is not "Erlang/OTP's team problem" per se but you may consider signing your installer and uninstaller, if that's not the case. In some environments, that's effectively mandatory and without artefact signing, in some environments Erlang (and, sadly, RabbitMQ by extension) would not be considered.

**Comment by ophirzk** [comment]
@michaelklishin can it be backported to 3.13.*?
@IngelaAndin Digital signature confirms the integrity of the executable. As @michaelklishin said, many systems will refuse to let RabbitMQ run because it is not signed and the publisher (the owner of the product) cannot be verified. Basically, anyone can create their own RabbitMQ and claim it is the original one. Without signing, there is no way to know. Same way when you open your browser and go to github and it returns you a signed certificate so your browser can verify it is indeed github. You can know it is github **only ** based on the certificate and your browser trusts it only because it trusts the certificate authority signed it. If github were to stop using a certificate your browser (at least in its default configurations) would not let you go to github. The  same goes for executables. If they are not signed, in many cases no one will be willing to install it in the first place, or it will be blocked.

**Comment by michaelklishin** [comment]
I have cherry-picked it to `v3.13.x`, that does not existing `3.13.x` releases, their artifacts will not be re-built or signed. `3.13.8` and later releases should be signed the same way https://github.com/rabbitmq/rabbitmq-server-binaries-dev/releases/tag/v4.0.0-alpha.181 is.

**Comment by lukebakken** [comment]
@ophirzk - I downloaded an official OTP installer from [here](https://github.com/erlang/otp/releases/download/OTP-26.2.5.2/otp_win64_26.2.5.2.exe), and verified that all `.exe` files are digitially signed (including the installer itself), except what will become `uninstall.exe`.

This shouldn't be a big deal - you can _ALWAYS_ immediately delete that file after installing Erlang, and then come up with a script (powershell, for instance), to do the uninstallation. The installer is extremely simple and "cleaning up" the registry and file system via a script would be very easy to do. Just an option for you.

cc @IngelaAndin
